version: '3'
services:
    converter:
        build: .
        ports:
            - "5002:5002"
        environment:
            - BACKEND_URL=host.docker.internal:5000
            - API_URL=host.docker.internal:5001
            - CONVERTER_URL=host.docker.internal:5002
            - WORKER_URL=host.docker.internal:5003
            - REDIS_URL=host.docker.internal:6379
            - DATABASE_URL=postgresql://postgres:DreamTeam123*@35.224.243.237:5432/postgres
            - MAIL_URL=host.docker.internal:5004